modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
issueTrackerURL="https://github.com/Starexify/HexxiGearR/issues"

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

logoFile="hexxit_gear_r_logo.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''
license="${mod_license}"

[modproperties.modmenu]
links=["hexxit_gear.modrinth=modrinth.com/mod/hexxit_gear_r", "hexxit_gear.curseforge=www.curseforge.com/minecraft/mc-mods/hexxit-gear-r"]
sources="https://github.com/Starexify/HexxiGearR"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
